# Generated by Django 3.0.7 on 2020-06-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotyledon', '0002_event_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotyledon.Bed'),
        ),
        migrations.AddField(
            model_name='event',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotyledon.Plant'),
        ),
    ]
