# Generated by Django 3.0.7 on 2020-06-09 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotyledon', '0003_auto_20200609_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cotyledon.Plant'),
        ),
    ]
