# Generated by Django 3.0.7 on 2020-06-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotyledon', '0006_auto_20200609_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
