# Generated by Django 3.0.7 on 2020-06-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotyledon', '0008_auto_20200609_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('sow', 'Sow'), ('transplant', 'Transplant'), ('harvest', 'Harvest'), ('destroy', 'Destory')], max_length=255),
        ),
    ]
